services:
  ruby_service:
    container_name: ruby_service
    build:
      context: .
      dockerfile: Dockerfile.ruby
    environment:
      - SLIDE_SPEAK_API_KEY=${SLIDE_SPEAK_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  python_service:
    container_name: python_service
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - SLIDE_SPEAK_API_KEY=${SLIDE_SPEAK_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
